_wandb:
    value:
        cli_version: 0.24.2
        e:
            w3faqt1osc7zduso0nnslgrwo9vsvg3n:
                codePath: /Users/joannachang/Documents/26 Spring/ML in production/Labs/cmu-mlip-model-testing-lab/lab4.ipynb
                codePathLocal: lab4.ipynb
                email: joannac2@andrew.cmu.edu
                executable: /opt/anaconda3/bin/python
                git:
                    commit: cb0af0bb0d0a2d62a061555180629503b0cb88c2
                    remote: https://github.com/nikitachaudharicodes/cmu-mlip-model-testing-lab.git
                host: MacBook-Pro-363.local
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/joannachang/Documents/26 Spring/ML in production/Labs/cmu-mlip-model-testing-lab/lab4.ipynb
                python: CPython 3.12.2
                root: /Users/joannachang/Documents/26 Spring/ML in production/Labs/cmu-mlip-model-testing-lab
                startedAt: "2026-02-05T14:54:53.145749Z"
                writerId: w3faqt1osc7zduso0nnslgrwo9vsvg3n
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 100
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 100
                - 105
            "3":
                - 2
                - 13
            "4": 3.12.2
            "5": 0.24.2
            "6": 4.57.1
            "8":
                - 1
            "10":
                - 20
            "12": 0.24.2
            "13": darwin-arm64
